#!/bin/sh

TARGET = libhknfcrwp.a

SRCDIR = ./src
OBJDIR = ./obj
INCDIR = ./inc

SRCS = \
	misc.cpp \
	devaccess_pasori.cpp \
	HkNfcA.cpp \
	HkNfcB.cpp \
	HkNfcF.cpp \
	HkNfcDep.cpp \
	HkNfcLlcpI.cpp \
	HkNfcLlcpT.cpp \
	NfcPcd.cpp \
	HkNfcRw.cpp

OBJS = $(addprefix $(OBJDIR)/, $(SRCS:.cpp=.o))
SRCP = $(addprefix $(SRCDIR)/, $(SRCS))
vpath %.cpp $(SRCDIR)


CFLAGS = -I$(INCDIR) -Wextra -O3
LDOPT  = 

# rules

all: $(TARGET)

$(TARGET): $(OBJS)
	$(AR) r $(TARGET) $(OBJS)

$(OBJDIR)/%.o : %.cpp
	$(CXX) -o $@ -c $(CFLAGS) $<

clean:
	$(RM) $(OBJDIR)/*.o $(TARGET) .Depend

.DependP:
	-$(CXX) $(CFLAGS) -MM $(SRCP) > .tmp
	@if [ ! -d $(OBJDIR) ]; then \
		echo ";; mkdir $(OBJDIR)"; mkdir $(OBJDIR); \
	fi
	sed -e '/^[^ ]/s,^,$(OBJDIR)/,' .tmp> .DependP
	rm .tmp

include .DependP
